'use client';
import './globals.css';
import AppSidebar from "@/components/app-sidebar"
import SplashScreen from "@/components/splash-screen"
import { useEffect, useState } from "react";
import { metadata } from "@/constants/metadata";
import Header from '@/components/header';
import AuthProvider from '@/components/auth/auth-provider';
import { SessionProvider, useSession } from 'next-auth/react';
import { redirect } from 'next/navigation';


// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [showSplash, setShowSplash] = useState(true);
  // const {data: session, status} = useSession();
  // const router = useRouter();
  const [isAuthenticated, setIsAuthenticated] = useState(false);

  useEffect(() => {
    if (isAuthenticated) {
      // router.push('/login');
      redirect('/login');
    }
  }, []);

  // if(status === 'loading') return <div>loading ...</div>

  return (

    <html lang="en">
      <body className="flex items-start justify-between">
        <main className='grid w-full h-full'>
          {children}
        </main>

      </body>
    </html>

  )
}
